In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[ 'the glass of milk',
      'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaning of words',
       'your videos are good',

]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
##Define the vocabulary size
voc_size =10000

In [ ]:
###One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2657, 5609, 4732, 2125],
 [2657, 5609, 4732, 9656],
 [2657, 2327, 4732, 1267],
 [1700, 3445, 1506, 838, 4570],
 [1700, 3445, 1506, 838, 4597],
 [1062, 2657, 7023, 4732, 5125],
 [4603, 1834, 4489, 838]]

In [ ]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [33]:
import numpy as np

In [34]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2657 5609 4732 2125]
 [   0    0    0    0 2657 5609 4732 9656]
 [   0    0    0    0 2657 2327 4732 1267]
 [   0    0    0 1700 3445 1506  838 4570]
 [   0    0    0 1700 3445 1506  838 4597]
 [   0    0    0 1062 2657 7023 4732 5125]
 [   0    0    0    0 4603 1834 4489  838]]


In [35]:
## feature representation
dim=10# for 10 features


In [38]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))

model.compile('adam','mse')

In [39]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.00888033,  0.03062949, -0.0448764 ,  0.01047868,
         -0.03260628,  0.01121153,  0.00290543, -0.02765107,
         -0.04798968,  0.03071565],
        [ 0.01740136, -0.00744066,  0.03062725, -0.00139483,
          0.02396477,  0.0080872 ,  0.02169557,  0.02312605,
          0.03942302,  0.02930372],
        [ 0.04266275, -0.01209296,  0.03286846,  0.0

In [41]:
embedded_docs[0]  #first sentence with 4 words

array([   0,    0,    0,    0, 2657, 5609, 4732, 2125], dtype=int32)

In [44]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[[ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.02918461,  0.00161979, -0.03210993,  0.04361456,
         -0.01902115, -0.04142202,  0.02260034,  0.02456447,
         -0.04772374, -0.0385474 ],
        [ 0.00888033,  0.03062949, -0.0448764 ,  0.01047868,
         -0.03260628,  0.01121153,  0.00290543, -0.02765107,
         -0.04798968,  0.03071565],
        [ 0.01740136, -0.00744066,  0.03062725, -0.00139483,
          0.02396477,  0.0080872 ,  0.02169557,  0.02312605,
          0.03942302,  0.02930372],
        [ 0.04266275, -0.01209296,  0.03286846,  0.0